//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEducation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.Feeds = new HashSet<Feed>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string Updateuser { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> ImageLink { get; set; }
        public Nullable<int> CommentControlId { get; set; }
        public Nullable<int> LikeIControld { get; set; }
    
        public virtual CommentControl CommentControl { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual LikeControl LikeControl { get; set; }
        public virtual ICollection<Feed> Feeds { get; set; }
    }
}
