//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEducation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeControl
    {
        public LikeControl()
        {
            this.Documents = new HashSet<Document>();
            this.Lessons = new HashSet<Lesson>();
            this.Likes = new HashSet<Like>();
        }
    
        public int Id { get; set; }
        public string ImageLink { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
    }
}
