//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEducation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public Like()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CreateUser { get; set; }
        public string Updateuser { get; set; }
        public Nullable<int> LikeControlId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual LikeControl LikeControl { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
