//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEducation.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UzaktanEgitimEntities : DbContext
    {
        public UzaktanEgitimEntities()
            : base("name=UzaktanEgitimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comment> Comments { get; set; }
        public DbSet<CommentControl> CommentControls { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<Feed> Feeds { get; set; }
        public DbSet<Lesson> Lessons { get; set; }
        public DbSet<Like> Likes { get; set; }
        public DbSet<LikeControl> LikeControls { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleScreenMap> RoleScreenMaps { get; set; }
        public DbSet<RoleUser> RoleUsers { get; set; }
        public DbSet<Screen> Screens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserLessonMap> UserLessonMaps { get; set; }
        public DbSet<Video> Videos { get; set; }
    }
}
